vim.keymap.set("n", "<leader>,api",":-1r $HOME/.config/nvim/lua/config/snippets/api-template<CR> gg_2wcw" )
vim.keymap.set("n", "<leader>,sql",":-1r $HOME/.config/nvim/lua/config/snippets/sql-setup<CR> gg/table1<CR>cw" )
vim.keymap.set("n", "<leader>,comp",":-1r $HOME/.config/nvim/lua/config/snippets/react-component<CR> :%s/Component/" )
vim.keymap.set("n", "<leader>,dockerc",":-1r $HOME/.config/nvim/lua/config/snippets/docker-compose<CR> gg" )
vim.keymap.set("n", "<leader>,dockerf",":-1r $HOME/.config/nvim/lua/config/snippets/docker-file<CR> gg" )
